backend:
  name: gitlab
  repo: freiheit-staging/freiheit
  branch: main
  auth_type: pkce
  app_id: bfb39d53bbdf536cc50a7a2a044bca7d697db995d1f3c9acd8ba5912a2bb9290
media_folder: static/img
public_folder: /img
collections:
  - name: join-us
    label: Join Us
    folder: content/join-us
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    exclude: [ _index.md ]
    view:
      fields: [ title, date, weight, draft ]
    fields:
      - { name: title, label: Title, widget: string }
      - { name: datetime, label: Date, widget: datetime, date_format: YYYY-MM-DD, picker_utc: true }
      - { name: draft, label: Draft, widget: boolean, default: false }
      - { name: weight, label: Order, widget: number, value_type: int, default: 1 }
      - { name: body, label: Body, widget: markdown, modes: ["raw"] }