googleAnalytics:
  anonymizeIP: true
  disable: false
  respectDoNotTrack: true
  useSessionStorage: false
instagram:
  disable: true
  simple: false
x:
  disable: true
  enableDNT: false
  simple: false
vimeo:
  disable: false
  enableDNT: true
  simple: true
youtube:
  disable: false
  privacyEnhanced: true